name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: beammp_manager_ubuntu.zip
            asset_name: beammp_manager_ubuntu
          - os: windows-latest
            artifact_name: beammp_manager_windows.zip
            asset_name: beammp_manager_windows
    runs-on: ${{ matrix.os }}

    env:
      MAIN_PY_FILE: 'src/run.py'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.x

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build executable directory
        run: uv run pyinstaller --name beammp_manager --add-data "static:static" --add-data "templates:templates" ${{ env.MAIN_PY_FILE }}

      - name: Add example .env file
        run: cp .env.example dist/beammp_manager

      - name: Zip directory
        working-directory: dist/beammp_manager
        run: 7z a ${{ matrix.artifact_name }} *

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/beammp_manager/${{ matrix.artifact_name }}
          overwrite: true
          archive: false

      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/beammp_manager/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}_${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          draft: true
          overwrite: true
